name: Deploy to s3
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      
    steps: 
    - uses: actions/checkout@main
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm install, build
      run: |
        npm install
        npm run build
        
    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: dist
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
